generator/src/control.ml
The virtual_allocation can be computed from the VDIs anyway.
=> SR.stat: use total_space, free_space i.e. the same as SMAPIv2

generator/src/control.ml, generator/src/data.ml, generator/src/ocaml.ml, generator/src/python.ml, python/Makefile
This can be done in 2 different ways:
If the datapath supports it naturally (e.g. tapdisk + vhd deltas), then the datapath `Plugin.Query` should expose capability `NONPERSISTENT` and implement `Datapath.open` and `Datapath.close`.
When a VM starts we will execute
- `Datapath.open`
- `Datapath.attach`
- `Datapath.activate`
When a VM migrates we will execute
- `Datapath.attach`
- `Datapath.deactivate`
- `Datapath.activate`
- `Datapath.detach`
When a VM shuts down we will execute
- `Datapath.deactivate`
- `Datapath.detach`
- `Datapath.close`
This also adds the ability to store arbitrary key=value pairs with the Volumes. These key = value pairs are intended for the higher-level software only i.e. they are not interpreted by the plugin implementations. These will be used to implement …
=> API changes for clone-on-boot

generator/src/control.ml
For storage systems which have a pre-existing notion of a UUID/GUID,
allow the Volume.stat to return it (which in turn can be used by
higher-level tools like xapi). Note that a UUID/GUID is entirely optional.
=> Add an optional Volume.uuid

generator/src/plugin.ml
Some storage implementations will require the use of a cluster stack;
for example OCFS2 requires either O2CB or pacemaker/corosync. This
will allow higher-level software to configure the necessary cluster
stack before creating and using any storage.
=> Add a `required_cluster_stack` list

generator/src/control.ml
These should point to xenostat-format shared memory pages containing
time-varying data. Suitable uses include
- free space in the SR
- I/O latency
=> Add per-SR datasource URIs

python/xapi/__init__.py
`handle_exception` can return an xcp-idl `Backend_error_with_backtrace`
which includes:
- XenAPI error code (optional, defaults to `SR_BACKEND_ERROR`)
- XenAPI error params
- error backtrace
=> Update `handle_exception` to send back XenAPI errors

generator/src/control.ml
SR.probe takes a `uri` argument which could be `iscsi://target` and
then returns a struct with
- SRs: this means I found specific SRs (great!)
- URIs: this means I have some suggestions for related URIs you could
try. This could be 'scsi://target/iqn'. The client could then
perform `SR.probe` calls with these URLs to explore the storage.
=> Add SR.probe

generator/src/control.ml
* Clustered implies that the SR uses aggregrated local storage, where "local"
refers to the disks that are inside the XenServer hosts.
* The "health" field provides a way for the storage backend to signal to the
toolstack whether the storage is currently degraded and being repaired in some
way (e.g. by rebuilding RAID mirrors).
Signed-off-by: Rob Hoes <rob.hoes@citrix.com>
=> Add new fields to SR.stat: "clustered" and "health"

python/xapi/storage/log.py
This commit contains two changes:
- Don't log the timestamp explicitly, as syslog already adds this implicitly.
- Flag log-entries as belonging to SMAPIv3 - this is similar to SMAPIv1
flagging as SM.
Signed-off-by: Robert Breker <robert.breker@citrix.com>
=> Clean up xapi.storage.log log-entries

.travis.yml, opam
This is a really "brute-force" pull request for fixing the Travis CI build, as I've simply restricted the `cow` package to older versions, and removed a command-line argument from the `flake8` invocation - feel free to close it if you think adapting the code to work with the new `cow` package is more appropriate.
=> Fix Travis CI build

opam
rpc requires cow > 2.0.0 to build (fails with 1.4.0), and xapi-storage requires
cow < 2.0.0.
But obviously we are able to build both using the .spec  files, so fix the opam
dependency to allow co-installation with rpc.
After this  change I was able to pin and install both xapi and xapi-storage in the same opam switch.
=> fix opam dep conflict with rpc

python/xapi/__init__.py
If the backend raises a subclass of Rpc_light_failure we were
only passing through the arguments, but not the actual exception name.
So the caller had no way to tell which exception we raised.
We need to know the correct exception when we raise the snapshot redirect
exception, otherwise XAPI just receives a generic exception it doesn't know what
to do with:
result.contents: ["Backend_error_with_backtrace",["SR_BACKEND_FAILURE",["{\"error\":\"7fe5d42c-e165-4814-8263-2408cd132a61\"
This is related to the exception transformation we discussed with @gaborigloi 
Signed-off-by: Edwin Török <edvin.torok@citrix.com>
=> CA-272163: do not lose exception type during RPC

generator/src/control.ml
When doing SR.create the SM can put the uuid into the uri it returns,
however with SR.introduce we don't have the uuid inside the uri.
Always pass the uuid explicitly to attach so that both create and introduce
works.
This needs to be merged together with the xapi-storage-script PR.
=> SR.attach uuid

generator/lib/control.ml, generator/lib/ocaml.ml, generator/lib/python.ml, generator/lib/types.ml, python/xapi/__init__.py
This is part of the SMAPIv3 interface  change from `feature/REQ477/master`,
has to be merged together with these PRs:
xapi-project/sm-cli#26
xapi-project/xapi-storage-script#56
xapi-project/xcp-idl#202
https://github.com/xapi-project/xen-api/pull/3433
The sharable flag is explained in the xcp-idl commit: https://github.com/xapi-project/xcp-idl/commit/c8bfaf9d61c547df42fac12f5d05b0165e24b83b
SMAPIv3:
The activated on exception/redirection is explained here (SMAPIv3 can require snapshots to be taken on the host that has the VM running, instead of the master): https://github.com/xapi-project/xen-api/commit/620acd20e2753a7f10a970e6f1850b325fea082a
SMAPIv2 uses a similar mechanism internally to redirect requests to the master (e.g. in case of storage migration).
=> [477 idl part2] sharable flag, SR.create/SR.attach API change, introduce redirection exception

generator/lib/types.ml
Signed-off-by: Akanksha Mathur <akanksha.mathur@citrix.com>
=> Remove redundant definition of function pipe (|>)

.travis.yml, generator/lib/python.ml, generator/src/main.ml, python/jbuild, python/setup.py, python/xapi/__init__.py, python/xapi/storage/api/datapath.py, python/xapi/storage/api/plugin.py, python/xapi/storage/api/v4/__init__.py, python/xapi/storage/api/volume.py
The already shipped supp-pack with the tmpfs SR imports a python library from
the installed host.
If we update the host without updating the supp-pack we need to keep the python
library backward compatible.
The short-term fix is to keep the old library as was, and put the new library
into a different module.
In the future the code generator can be updated to generate a single python
module that is  compatible with all the APIs.
Need to be merged together with:
https://github.com/xapi-project/xapi-storage-script/pull/57
(and the internal PR on the spec files)
=> CA-283728: put generated code into new namespace

ocaml/lib_test/storage_test.ml, rpc-light/volume.create/request, rpc-light/volume.create/response
We haven't noticed that the tests were failing on master, because the tests were exiting with code 0 after a failure. Fix that and the actual test failure.
=> Fix tests on xapi-storage master

generator/html/www.ml
Caml2html outputs a string containing html tags, which were escaped by
Cow, and therefore the HTML source of the syntax-highlighted OCaml code
was displayed as plain text.
Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>
=> generator/html: fix ocaml code example syntax highlight

generator/lib/control.ml, generator/lib/python.ml
Part of a series of PR, main PR here: https://github.com/xapi-project/xcp-idl/pull/217
Changes API of SMAPIv3  SR.create and SR.attach to take a device-config map instead of a JSON serialized into a string and called 'uri'.
Probe will return the device-config needed for SR.create/SR.attach.
Backwards compatibility with existing SMAPIv3 plugins is handled in the xapi-storage-script PR: `xapi-storage` always declares the latest APIs and xapi-storage-script takes care of translating the requests/responses in a backward compatible way.
=> review probe API changes to feature/REQ477/master

python/xapi/storage/common.py
Especially in their handling of unicode string, with .format being better.
So, convert the logging in call to use this to avoid getting incorrect errors in failure conditions, otherwise an unhelpful error of the form `UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 28: ordinal not in range(128)` is produced, instead of what actually went wrong in the process call.
Generally tidy up some python style issues as well.
Signed-off-by: Mark Syms <mark.syms@citrix.com>
=> CA-283254: formatting strings with % and .format differ

generator/lib/plugin.ml
This is a minor fix and emphasizes that every plugin, datapath as well
as volume plugins need to implement the query interface. For me it was
too easy to overlook that in the documentation.
Closes xapi-project/xapi-storage-script#79.
=> doc,plugin: All plugins need to satisfy query interface

generator/lib/common.ml, generator/lib/data.ml, generator/lib/plugin.ml, generator/lib/task.ml
Doc building was broken using odoc, changing to ocamldoc tags fixes it.
The documentation was manually checked, same as https://github.com/xapi-project/xcp-idl/pull/300
=> maintenance: fix doc generation
